# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f93680f6e2af1a07d9d6251ebbe697d76335d17a4496840538bcc6b13024bc82894fefdfe58eadcb106c9159190d80ff69e04544f970ab9f879cbad88d73ace7

test:
  secret_key_base: bb334916b917a65a15708414e88f15902f638469294ba6eab8481292e8ae93011aea36c8a8b0a7a0038a5cdf6792191d778a75216481cf32372dee0a6b044a8e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
